// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4QNfTbxxzdTrPWFOsKDSE76owS-598k',
    appId: '1:767603596191:android:7744f17da315dfb304bbaa',
    messagingSenderId: '767603596191',
    projectId: 'fir-task-35274',
    databaseURL: 'https://fir-task-35274-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-task-35274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpZjfcnjVHG-Zfl295hBv4cZBJr4VTOo',
    appId: '1:767603596191:ios:ce27fb9ba61a0a5b04bbaa',
    messagingSenderId: '767603596191',
    projectId: 'fir-task-35274',
    databaseURL: 'https://fir-task-35274-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-task-35274.appspot.com',
    iosClientId: '767603596191-3li7l68l3rlkvtl77sgnp9na025evl25.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );
}
